### ISSUE TITLE
Random numbers into register

### ISSUE THREAD

**Issue by Welsyntoffie** [botura/IO-remoto#1]
I am having some issues where some of my modbus registers are filled with random numbers.
Like mbdata[28] which is a setpoint and should be 3. But now contains 28974. When I attempt to change to 3 is does not and keeps the larger number. I have close to 120 registers.
So I then found this "#define MbDataLen 30 // length of the MdData array"
I changed from 30 to 350. The random numbers in some registers did stop and now all is working for several days non stop.
The problem with this now is that it consumes allot of memory 15% more.

Is this the right way to go about it? Is there something else I should consider?

**Comment by botura** [comment]
It is the right way to go with, you have to reserve the memory that will be used with modbus, otherwise this positions will be available and the compiler might use it for temporary variables.
